### ISSUE TITLE
Save data erased after updating games

### ISSUE THREAD

**Issue by wawvyy** [whitewhidow/quest-sidenoder#34]
Games losing save data after updating

I just did the normal method of going to the installed apps section and upon updating Blaston (2 days ago) and In Death: Unchained (today) I opened the games to find that none my other saves were there.

Running : 
 - OS: Windows
 - Version v0.0.6-alpha

**Comment by whitewhidow** [comment]
The data backup and restore does not work for all games, so im not sure about blaston, HOWEVER, for "in death" it should update normally without losing data i think it just stores in "com.Solfar.InDeath", unless it has changed to "internal data" recently 

ill do a test myself tmrw with that specific title, thx for reporting.

**Comment by whitewhidow** [comment]
hi srry due to lack of hmd i havent been able to test it yet , but someone else has reported the same thing, and there is also something fishy going on with the versionnumbers as far as in death goes...   so no progress so far,  but not forgotten

**Comment by whitewhidow** [comment]
Could you please retry using v0.0.10
https://github.com/whitewhidow/quest-sidenoder/releases/tag/v0.0.10

thx and sorry for the slow reply

**Comment by whitewhidow** [comment]
Please check if fixed in 
https://github.com/whitewhidow/quest-sidenoder/releases/tag/v0.0.12

**Comment by Dzago-cell** [comment]
Can confirm that the issue is still there. Updated In Death on v0.0.12 to have all save files be deleted from data folder.

**Comment by whitewhidow** [comment]
I just tested this myself..

the following files are backed up and restored:

doing adb pull appdata (ignore error)
pull: building file list...
**[ 29%] /sdcard/Android/data/com.Solfar.InDeath/files/cloud/data/SaveGames/Settings.sav: 100%
[ 49%] /sdcard/Android/data/com.Solfar.InDeath/files/cloud/data/SaveGames/General.sav: 100%
[100%] /sdcard/Android/data/com.Solfar.InDeath/files/cloud/data/SaveGames/PlayerProgressGD.sav: 100%**
/sdcard/Android/data/com.Solfar.InDeath/: 3 files pulled. 0.0 MB/s (6034 bytes in 0.255s)

doing adb uninstall (ignore error)
Success

doing adb push appdata (ignore error)
**[ 50%] /PlayerProgressGD.sav: 100%
[ 80%] /sdcard/Android/data/com.Solfar.InDeath/files/cloud/data/SaveGames/Settings.sav: 100%
[100%] /sdcard/Android/data/com.Solfar.InDeath/files/cloud/data/SaveGames/General.sav: 100%**
/tmp/sidenoder_restore_backup/com.Solfar.InDeath/files/: 3 files pushed. 1 file skipped. 0.3 MB/s (6034 bytes in 0.017s)


Confirmed afterwards that the files are present
**adb shell ls /sdcard/Android/data/com.Solfar.InDeath/files/cloud/data/SaveGames
General.sav
PlayerProgressGD.sav
Settings.sav**


and the savegame is also still present for me ..
not sure what could be going wrong for you ....  any chance you still have the game running while trying to update or something?

As it most certainly seems to work fine for 99% of the users, including myself

**Comment by Dzago-cell** [comment]
Interesting. I will test some more

**Comment by whitewhidow** [comment]
also,  just for info, in case it is usefull somehow,   
after updating, there should also be a folder named 'sidenoder_restore_backup' left inside your machines TMP folder (location depends on your os), this folder should also hold a backup of the data that has been backed up and restored.

These are the files that are placed back onto the headset, manually restoring these should also restore your data. (but this is the process that should already have been taken done sidenoder, but worth a shot to test)

**Comment by Dzago-cell** [comment]
I did backup manually but I also did find the folder with backups that you spoke of.
Not sure why it is not working for me. I installed an older version dropped in my saves and updated. Same issue, no save files. Game was not running during the update.
Not sure if it only happens for this game or for the others as well for me, this was the only one that needed an update and had save files.

**Comment by whitewhidow** [comment]
any chance you could run the NPM version ?
(this will show actual errors in the concole) (im suspecting a windows-related backslash-issue here)

**Comment by Dzago-cell** [comment]
Sure, I can do that. What and where should I be looking for?

**Comment by whitewhidow** [comment]
Instructions for running with npm (instead of the exe) are here :
https://github.com/whitewhidow/quest-sidenoder#manually-run-using-node-on-windows

(if you end up needing manual help with this: https://discord.gg/pVMsAyYhAf)

**Comment by Dzago-cell** [comment]
Running is not the issue, more of where to look for the necessary info.
I found this, if you need something else do let me know where to look for it.

attempting to read package info
package info read success (com.Solfar.InDeath)
checking if installed
exec_stdout
package:com.Solfar.InDeath

doing adb pull appdata (ignore error)
exec_stdout
/sdcard/Android/data/com.Solfar.InDeath/: 4 files pulled, 0 skipped. 0.7 MB/s (19359 bytes in 0.028s)

doing adb uninstall (ignore error)
exec_stdout
Success

doing adb push appdata (ignore error)
exec_stderr

exec_error
exec_stdout
adb: error: cannot stat 'C:/Users/vitvk/AppData/Local/Temp/sidenoder_restore_backup/com.Solfar.InDeath/*': No such file or directory

doing adb install
is remote, copying to C:/Users/vitvk/AppData/Local/Temp/In Death - Unchained [1.2.7.29764052] S2.11.apk
exec_stdout
Performing Streamed Install
Success

exec_error
exec_stderr
'rm' is not recognized as an internal or external command,
operable program or batch file.

DATAFOLDER to copy:com.Solfar.InDeath
doing obb rm
exec_error
exec_stderr
rm: /sdcard/Android/obb/com.Solfar.InDeath: No such file or directory

C:/Users/vitvk/AppData/Local/Temp/com.Solfar.InDeath already exists
obb File: C:/Users/vitvk/AppData/Local/Temp/mnt/In Death - Unchained v29764052+1.2.7 -QU -versionCode-29764052 -packageName-com.Solfar.InDeath -steam-605450/com.Solfar.InDeath/main.29764052.com.Solfar.InDeath.obb
doing obb push
obb is remote, copying to C:/Users/vitvk/AppData/Local/Temp/com.Solfar.InDeath/main.29764052.com.Solfar.InDeath.obb
exec_stderr

doing shell mv
exec_stderr

DONE

**Comment by whitewhidow** [comment]
thx,   so this first part seems to succe3ssfully PULL the data from the device:

> doing adb pull appdata (ignore error)
> exec_stdout
> /sdcard/Android/data/com.Solfar.InDeath/: 4 files pulled, 0 skipped. 0.7 MB/s (19359 bytes in 0.028s)

But then the following part seems to fail when trying to pull them back onto the device after the uninstall:
> exec_error
> exec_stdout
> adb: error: cannot stat 'C:/Users/vitvk/AppData/Local/Temp/sidenoder_restore_backup/com.Solfar.InDeath/*': No such file or directory

is the directory `C:/Users/vitvk/AppData/Local/Temp/sidenoder_restore_backup/com.Solfar.InDeath/` not the correct path to where it saved the backup ?

also,   what happens when you manually try to push the backup data using:
`adb push C:/Users/vitvk/AppData/Local/Temp/sidenoder_restore_backup/com.Solfar.InDeath/* /sdcard/Android/data/com.Solfar.InDeath/`
Does this indeed fail the same way (it should, as this is the command used)?

**then**, please check what happens when quotes are added as so :
`adb push "C:/Users/vitvk/AppData/Local/Temp/sidenoder_restore_backup/com.Solfar.InDeath/*" "/sdcard/Android/data/com.Solfar.InDeath/"`

Do these quotes fix the issue on windows ?

thx in advance.

**Comment by whitewhidow** [comment]
> If I do something like these it works:
> `adb push C:/Users/vitvk/AppData/Local/Temp/sidenoder_restore_backup/com.Solfar.InDeath/ /sdcard/Android/data/`

and is the data actually indeed properly restored after this ?
If so, i will make the change and build a new release

thx again

**Comment by Dzago-cell** [comment]
Looks like it. Booted the game, saves are there.

**Comment by whitewhidow** [comment]
> Looks like it. Booted the game, saves are there.

thx,

Could you please verify that it works in compiled build v0.0.13 (pre-release): 
https://github.com/whitewhidow/quest-sidenoder/releases/download/v0.0.13/sidenoder-win-x64-exe.zip

if so, i will promote it to stable so that everyone gets the update prompt.

**Comment by Dzago-cell** [comment]
I updated and my saves were there.
Thank you.

**Comment by whitewhidow** [comment]
thx,  fixed in stable release https://github.com/whitewhidow/quest-sidenoder/releases/tag/v0.0.13

closing ticket
